title: SadOmeisaurus
email: ""
description: CTF Player, Bug Hunter, Frontend developer
baseurl: "/my_blog"
url: ""
twitter: ""
github:  ""
telegram: "https://t.me/SadOmeisaurus"
scss:
  style: compressed